name: saigai01
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  firebase_auth: ^3.11.2
  firebase_analytics: ^9.3.8
  cloud_firestore: ^3.5.1
  flutter_svg: ^1.1.5
  google_maps_flutter: ^2.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  firebase_storage: ^10.3.11
  cached_network_image: ^3.2.2
  scrollable_positioned_list: ^0.3.5
  dio: ^4.0.6
  firebase_messaging: ^13.1.0
  photo_view: ^0.14.0
  image_cropper: ^3.0.1
  connectivity_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.0.3
  json_serializable: ^6.5.3
  freezed: ^2.2.0

flutter:  
  uses-material-design: true 
  assets:    
    - assets/img/
    - assets/jsons/google_map_style.json
    - assets/jsons/iwate.geojson
    - assets/img/toppage_icon.jpg

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/img/toppage_icon.jpg"


flutter_gen:
  output: lib/gen/

