// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDkP8T-pDiT-ScqzaUU3aD1W3tfKku8VE',
    appId: '1:741564189485:web:19bb73a7086943233161a4',
    messagingSenderId: '741564189485',
    projectId: 'saigai01-f648e',
    authDomain: 'saigai01-f648e.firebaseapp.com',
    storageBucket: 'saigai01-f648e.appspot.com',
    measurementId: 'G-ZZTQDBQBJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38Qm3gns8KxJUsWZIyyp74Q5WOvk8j8g',
    appId: '1:741564189485:android:408528f97b8166e83161a4',
    messagingSenderId: '741564189485',
    projectId: 'saigai01-f648e',
    storageBucket: 'saigai01-f648e.appspot.com',
  );
}
